name: text_theme_extensions
description: Helpers for removing boilerplate code on Flutter's TextTheme
version: 1.0.1
homepage: https://github.com/feinstein/text_theme_extensions
repository: https://github.com/feinstein/text_theme_extensions
topics:
  - theme
  - text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
